name: Java CI
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false # this is required for the deploy plugin
      - name: Set up JDK 8 ğŸ§
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages ğŸ“¦
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Python ğŸ
        uses: actions/setup-python@v1
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install python dependencies ğŸ
        run: pip install -r ./src/main/resources/requirements.txt
      - name: Build with Maven ğŸ—
        run: mvn -B package --file pom.xml
      - name: Coveralls ğŸ•µï¸â€
        run: mvn coveralls:report -DrepoToken=${{ secrets.COVERALLS }}
      - name: Generate Documentation ğŸ“š
        run: mvn javadoc:javadoc
      - name: Debug
        run: cd home/runner/work/jRDF2Vec/jRDF2Vec/target/site/apidocs && pwd
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: home/runner/work/jRDF2Vec/jRDF2Vec/target/site/apidocs
